/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          dark: '#070b19',
          card: '#0f152e',
          cyan: '#00f2fe',
          purple: '#7f00ff',
          pink: '#ff007f',
          green: '#00f5a0',
          yellow: '#ffd200',
          red: '#ef4444',
          accent: '#0d1530',
          lightBg: '#f8fafc',
          lightCard: '#ffffff',
          lightBorder: '#e2e8f0',
        },
        "primary-fixed-dim": "#cfbcff",
        "surface-variant": "#e6e0e9",
        "on-tertiary-container": "#503d00",
        "surface-container-high": "#ece6ee",
        "surface-container-highest": "#e6e0e9",
        "on-tertiary-fixed-variant": "#594400",
        "on-tertiary-fixed": "#241a00",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container": "#f2ecf4",
        "on-background": "#1d1b20",
        "primary-container": "#6750a4",
        "on-primary-fixed-variant": "#4f378a",
        "secondary-fixed-dim": "#cdc0e9",
        "tertiary": "#765b00",
        "surface-dim": "#ded8e0",
        "inverse-surface": "#322f35",
        "primary": "#4f378a",
        "secondary-container": "#e1d4fd",
        "background": "#fdf7ff",
        "on-surface-variant": "#494551",
        "secondary-fixed": "#e9ddff",
        "on-secondary-fixed-variant": "#4b4263",
        "on-primary": "#ffffff",
        "inverse-primary": "#cfbcff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#e7c365",
        "surface-container-low": "#f8f2fa",
        "on-primary-fixed": "#22005d",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e9ddff",
        "outline-variant": "#cbc4d2",
        "outline": "#7a7582",
        "secondary": "#63597c",
        "on-primary-container": "#e0d2ff",
        "surface-tint": "#6750a4",
        "tertiary-fixed": "#ffdf93",
        "on-error-container": "#93000a",
        "tertiary-container": "#c9a74d",
        "on-secondary-fixed": "#1f1635",
        "on-secondary-container": "#645a7d",
        "surface": "#fdf7ff",
        "surface-bright": "#fdf7ff",
        "on-secondary": "#ffffff",
        "on-surface": "#1d1b20",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f5eff7"
      },
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
        outfit: ['Outfit', 'sans-serif'],
      },
      boxShadow: {
        glow: '0 0 15px rgba(0, 242, 254, 0.35)',
        glowPurple: '0 0 15px rgba(127, 0, 255, 0.35)',
        glowGreen: '0 0 15px rgba(0, 255, 160, 0.35)',
        glowPink: '0 0 15px rgba(255, 0, 127, 0.35)',
      }
    },
  },
  plugins: [],
}
