import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'ar' | 'hi' | 'pt' | 'de' | 'ja';

type DictionaryType = Record<string, string>;

const TRANSLATIONS: Record<Language, DictionaryType> = {
  en: {
    // Nav / Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.bookTickets': 'Book Tickets',
    'nav.myBookings': 'My Bookings',
    'nav.chatbot': 'AI Stadium Chatbot',
    'nav.planner': 'AI Match Day Planner',
    'nav.announcements': 'AI Announcements',
    'nav.notifications': 'Notifications',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    // Home Dashboard
    'dash.welcome': 'Welcome back, World Cup Fan!',
    'dash.subtitle': 'Get ready for FIFA World Cup 2026. Manage your tickets, plan routes, and explore smart seat tools below.',
    'dash.upcomingMatches': 'Upcoming Matches',
    'dash.quickBooking': 'Quick Ticket Booking',
    'dash.announcements': 'Latest Announcements',
    'dash.updates': 'Stadium Updates',
    'dash.aiSuggestions': 'Personalized AI Suggestions',
    // Booking
    'book.title': 'FIFA Match Ticket Booking',
    'book.subtitle': 'Browse and secure tickets for major World Cup 2026 tournament matches.',
    'book.search': 'Search teams...',
    'book.filterStadium': 'Filter by Stadium',
    'book.filterDate': 'Filter by Date',
    'book.ticketPrice': 'Price',
    'book.available': 'seats left',
    'book.button': 'Book Tickets',
    'book.closed': 'Sales Closed',
    // Seat Selector
    'seat.title': 'Smart Seating Visualizer',
    'seat.subtitle': 'Choose sections and individual seats with interactive overlays.',
    'seat.available': 'Available',
    'seat.reserved': 'Reserved',
    'seat.booked': 'Booked',
    'seat.vip': 'VIP Seat',
    'seat.accessible': 'Accessible',
    'seat.finder': 'Smart Seat Finder',
    'seat.aiRecommend': 'AI Seat Recommendations',
    'seat.exitDist': 'Near Exit',
    'seat.foodDist': 'Near Food Court',
    'seat.wheelchair': 'Wheelchair accessible',
    'seat.family': 'Family area',
    'seat.budget': 'Budget seats',
    'seat.premium': 'Premium view',
    'seat.group': 'Group seating',
    'seat.total': 'Total',
    'seat.proceed': 'Confirm and Book',
    // My Bookings
    'my.title': 'My Match Tickets',
    'my.active': 'Active Tickets',
    'my.past': 'Past Tickets',
    'my.cancelled': 'Cancelled Bookings',
    'my.download': 'Download Ticket',
    'my.cancel': 'Cancel Booking',
    'my.refunded': 'Refunded',
    'my.gate': 'Gate',
    'my.seat': 'Seat',
    // Planner
    'plan.title': 'AI Match Day Planner',
    'plan.subtitle': 'Enter ticket gate and section coordinates to auto-build your route and concessions itinerary.',
    'plan.create': 'Generate Smart Timeline',
    'plan.gate': 'Ticket Gate',
    'plan.section': 'Section',
    'plan.row': 'Row',
    'plan.seatNum': 'Seat Number',
    'plan.parking': 'Parking Lot',
    'plan.kickoff': 'Kickoff Time',
    'plan.gatesOpen': 'Gates Open',
    'plan.pref': 'Itinerary Preference',
    'plan.bufferEarly': 'Arrive Early (Avoid Crowds)',
    'plan.bufferStd': 'Standard Buffer (1 Hour)',
    'plan.bufferTight': 'Tight Buffer (30 Mins)',
    'plan.situation': 'Situational Change or Delay?',
    'plan.adjust': 'Adjust Timeline',
    // Chatbot
    'chat.header': 'NexArena AI Assistant',
    'chat.placeholder': 'Ask me about parking, gates, halal food...',
    'chat.send': 'Send',
    // General
    'lang': 'Language',
  },
  es: {
    'nav.dashboard': 'Tablero',
    'nav.bookTickets': 'Reservar Boletos',
    'nav.myBookings': 'Mis Reservas',
    'nav.chatbot': 'Chatbot de IA del Estadio',
    'nav.planner': 'Planificador de IA del Partido',
    'nav.announcements': 'Anuncios de IA',
    'nav.notifications': 'Notificaciones',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configuración',
    'nav.logout': 'Cerrar sesión',
    'dash.welcome': '¡Bienvenido de nuevo, fan del Mundial!',
    'dash.subtitle': 'Prepárate para la Copa Mundial de la FIFA 2026. Administra tus boletos, planifica rutas y explora herramientas de asientos inteligentes.',
    'dash.upcomingMatches': 'Próximos Partidos',
    'dash.quickBooking': 'Reserva Rápida de Boletos',
    'dash.announcements': 'Últimos Anuncios',
    'dash.updates': 'Actualizaciones del Estadio',
    'dash.aiSuggestions': 'Sugerencias de IA Personalizadas',
    'book.title': 'Reserva de Boletos de la FIFA',
    'book.subtitle': 'Explore y asegure boletos para los partidos más importantes del torneo Mundial 2026.',
    'book.search': 'Buscar equipos...',
    'book.filterStadium': 'Filtrar por Estadio',
    'book.filterDate': 'Filtrar por Fecha',
    'book.ticketPrice': 'Precio',
    'book.available': 'asientos disponibles',
    'book.button': 'Reservar Asientos',
    'book.closed': 'Venta Cerrada',
    'seat.title': 'Visualizador de Asientos Inteligente',
    'seat.subtitle': 'Elija secciones y asientos individuales con superposiciones interactivas.',
    'seat.available': 'Disponible',
    'seat.reserved': 'Reservado',
    'seat.booked': 'Reservado/Vendido',
    'seat.vip': 'Asiento VIP',
    'seat.accessible': 'Accesible',
    'seat.finder': 'Buscador de Asientos Inteligente',
    'seat.aiRecommend': 'Recomendaciones de Asientos de IA',
    'seat.exitDist': 'Cerca de Salida',
    'seat.foodDist': 'Cerca de Comida',
    'seat.wheelchair': 'Acceso para Sillas de Ruedas',
    'seat.family': 'Área Familiar',
    'seat.budget': 'Asientos Económicos',
    'seat.premium': 'Vista Premium',
    'seat.group': 'Asientos Grupales',
    'seat.total': 'Total',
    'seat.proceed': 'Confirmar y Reservar',
    'my.title': 'Mis Boletos de Partido',
    'my.active': 'Boletos Activos',
    'my.past': 'Boletos Pasados',
    'my.cancelled': 'Reservas Canceladas',
    'my.download': 'Descargar Boleto',
    'my.cancel': 'Cancelar Boleto',
    'my.refunded': 'Reembolsado',
    'my.gate': 'Puerta',
    'my.seat': 'Asiento',
    'plan.title': 'Planificador del Día del Partido',
    'plan.subtitle': 'Ingrese la puerta y la sección para construir su ruta de llegada e itinerario.',
    'plan.create': 'Generar Horario Inteligente',
    'plan.gate': 'Puerta de Boleto',
    'plan.section': 'Sección',
    'plan.row': 'Fila',
    'plan.seatNum': 'Número de Asiento',
    'plan.parking': 'Estacionamiento',
    'plan.kickoff': 'Hora de Inicio',
    'plan.gatesOpen': 'Puertas Abren',
    'plan.pref': 'Preferencia de Itinerario',
    'plan.bufferEarly': 'Llegar temprano (Evitar multitudes)',
    'plan.bufferStd': 'Buffer estándar (1 hora)',
    'plan.bufferTight': 'Buffer ajustado (30 minutos)',
    'plan.situation': '¿Cambio de situación o retraso?',
    'plan.adjust': 'Ajustar Horario',
    'chat.header': 'Asistente de Inteligencia Artificial',
    'chat.placeholder': 'Pregúntame sobre estacionamiento, puertas, comida halal...',
    'chat.send': 'Enviar',
    'lang': 'Idioma',
  },
  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.bookTickets': 'Réserver des billets',
    'nav.myBookings': 'Mes réservations',
    'nav.chatbot': 'Assistant IA du Stade',
    'nav.planner': 'Planificateur IA du Match',
    'nav.announcements': 'Annonces IA',
    'nav.notifications': 'Notifications',
    'nav.profile': 'Profil',
    'nav.settings': 'Paramètres',
    'nav.logout': 'Déconnexion',
    'dash.welcome': 'Bon retour, fan de la Coupe du Monde !',
    'dash.subtitle': 'Préparez-vous pour la Coupe du Monde de la FIFA 2026. Gérez vos billets, planifiez vos itinéraires et explorez les outils de sièges intelligents.',
    'dash.upcomingMatches': 'Matchs à venir',
    'dash.quickBooking': 'Réservation rapide',
    'dash.announcements': 'Dernières annonces',
    'dash.updates': 'Mises à jour du stade',
    'dash.aiSuggestions': 'Suggestions IA personnalisées',
    'book.title': 'Réservation de billets FIFA',
    'book.subtitle': 'Parcourez et réservez des places pour les grands matchs de la Coupe du Monde 2026.',
    'book.search': 'Rechercher des équipes...',
    'book.filterStadium': 'Filtrer par stade',
    'book.filterDate': 'Filtrer par date',
    'book.ticketPrice': 'Prix',
    'book.available': 'sièges restants',
    'book.button': 'Réserver',
    'book.closed': 'Vente Clôturée',
    'seat.title': 'Visualisateur de sièges intelligent',
    'seat.subtitle': 'Choisissez les sections et les sièges avec des superpositions interactives.',
    'seat.available': 'Disponible',
    'seat.reserved': 'Réservé',
    'seat.booked': 'Occupé',
    'seat.vip': 'Siège VIP',
    'seat.accessible': 'Accessible',
    'seat.finder': 'Recherche de siège intelligente',
    'seat.aiRecommend': 'Recommandations de sièges par l\'IA',
    'seat.exitDist': 'Proche de la sortie',
    'seat.foodDist': 'Proche de la restauration',
    'seat.wheelchair': 'Accès fauteuil roulant',
    'seat.family': 'Espace famille',
    'seat.budget': 'Sièges économiques',
    'seat.premium': 'Vue Premium',
    'seat.group': 'Sièges de groupe',
    'seat.total': 'Total',
    'seat.proceed': 'Confirmer et Réserver',
    'my.title': 'Mes billets de match',
    'my.active': 'Billets actifs',
    'my.past': 'Billets passés',
    'my.cancelled': 'Réservations annulées',
    'my.download': 'Télécharger le billet',
    'my.cancel': 'Annuler la réservation',
    'my.refunded': 'Remboursé',
    'my.gate': 'Porte',
    'my.seat': 'Siège',
    'plan.title': 'Planificateur de match IA',
    'plan.subtitle': 'Saisissez vos coordonnées de billet et parking pour générer votre itinéraire intelligent.',
    'plan.create': 'Générer le calendrier',
    'plan.gate': 'Porte d\'entrée',
    'plan.section': 'Section',
    'plan.row': 'Rangée',
    'plan.seatNum': 'Numéro de siège',
    'plan.parking': 'Parking',
    'plan.kickoff': 'Coup d\'envoi',
    'plan.gatesOpen': 'Ouverture des portes',
    'plan.pref': 'Préférences d\'itinéraire',
    'plan.bufferEarly': 'Arriver tôt (Éviter la foule)',
    'plan.bufferStd': 'Marge standard (1 heure)',
    'plan.bufferTight': 'Marge serrée (30 minutes)',
    'plan.situation': 'Changement de situation ou retard ?',
    'plan.adjust': 'Ajuster l\'itinéraire',
    'chat.header': 'Assistant IA NexArena',
    'chat.placeholder': 'Posez vos questions sur le parking, les portes, la nourriture halal...',
    'chat.send': 'Envoyer',
    'lang': 'Langue',
  },
  ar: {
    'nav.dashboard': 'لوحة التحكم',
    'nav.bookTickets': 'حجز التذاكر',
    'nav.myBookings': 'حجوزاتي',
    'nav.chatbot': 'روبوت محادثة الاستاد',
    'nav.planner': 'مخطط يوم المباراة بالذكاء الاصطناعي',
    'nav.announcements': 'إعلانات الاستاد بالذكاء الاصطناعي',
    'nav.notifications': 'الإشعارات',
    'nav.profile': 'الملف الشخصي',
    'nav.settings': 'الإعدادات',
    'nav.logout': 'تسجيل الخروج',
    'dash.welcome': 'مرحباً بك مجدداً، مشجع كأس العالم!',
    'dash.subtitle': 'استعد لكأس العالم 2026. قم بإدارة تذاكرك وتخطيط مساراتك واستكشاف مقاعدك الذكية.',
    'dash.upcomingMatches': 'المباريات القادمة',
    'dash.quickBooking': 'الحجز السريع للتذاكر',
    'dash.announcements': 'آخر الإعلانات',
    'dash.updates': 'تحديثات الاستاد',
    'dash.aiSuggestions': 'توصيات مخصصة بالذكاء الاصطناعي',
    'book.title': 'حجز تذاكر مباريات الفيفا',
    'book.subtitle': 'تصفح واحجز تذاكر مباريات كأس العالم 2026.',
    'book.search': 'ابحث عن الفرق...',
    'book.filterStadium': 'تصفية حسب الاستاد',
    'book.filterDate': 'تصفية حسب التاريخ',
    'book.ticketPrice': 'السعر',
    'book.available': 'مقاعد متبقية',
    'book.button': 'حجز التذاكر',
    'book.closed': 'المبيعات مغلقة',
    'seat.title': 'معاين المقاعد الذكي',
    'seat.subtitle': 'اختر القطاعات والمقاعد الفردية بشكل تفاعلي بالكامل.',
    'seat.available': 'متاح',
    'seat.reserved': 'محجوز مؤقتاً',
    'seat.booked': 'محجوز',
    'seat.vip': 'مقعد VIP',
    'seat.accessible': 'ذوي الاحتياجات الخاصة',
    'seat.finder': 'مكتشف المقاعد الذكي',
    'seat.aiRecommend': 'ترشيحات المقاعد بالذكاء الاصطناعي',
    'seat.exitDist': 'قريب من المخرج',
    'seat.foodDist': 'قريب من المطاعم',
    'seat.wheelchair': 'مقعد كرسي متحرك',
    'seat.family': 'منطقة عائلية',
    'seat.budget': 'مقاعد اقتصادية',
    'seat.premium': 'إطلالة مميزة',
    'seat.group': 'مقاعد جماعية',
    'seat.total': 'الإجمالي',
    'seat.proceed': 'تأكيد وحجز المقاعد',
    'my.title': 'تذاكر المباريات الخاصة بي',
    'my.active': 'التذاكر النشطة',
    'my.past': 'التذاكر السابقة',
    'my.cancelled': 'الحجوزات الملغاة',
    'my.download': 'تحميل التذكرة',
    'my.cancel': 'إلغاء الحجز',
    'my.refunded': 'تم الاسترداد',
    'my.gate': 'البوابة',
    'my.seat': 'المقعد',
    'plan.title': 'مخطط يوم المباراة الذكي',
    'plan.subtitle': 'أدخل بوابة التذكرة وتفاصيل القطاع لبناء مسار الوصول الخاص بك.',
    'plan.create': 'إنشاء جدول زمني ذكي',
    'plan.gate': 'بوابة التذكرة',
    'plan.section': 'القطاع',
    'plan.row': 'الصف',
    'plan.seatNum': 'رقم المقعد',
    'plan.parking': 'موقف السيارات',
    'plan.kickoff': 'وقت ركلة البداية',
    'plan.gatesOpen': 'فتح البوابات',
    'plan.pref': 'أولوية الجدول',
    'plan.bufferEarly': 'الوصول مبكراً (تجنب الزحام)',
    'plan.bufferStd': 'وقت قياسي (ساعة قبل)',
    'plan.bufferTight': 'وقت ضيق (30 دقيقة قبل)',
    'plan.situation': 'تغير في الوضع أو تأخير؟',
    'plan.adjust': 'تعديل الجدول الزمني',
    'chat.header': 'مساعد الاستاد بالذكاء الاصطناعي',
    'chat.placeholder': 'اسألني عن مواقف السيارات، البوابات، الأكل الحلال...',
    'chat.send': 'إرسال',
    'lang': 'اللغة',
  },
  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.bookTickets': 'टिकट बुक करें',
    'nav.myBookings': 'मेरी बुकिंग',
    'nav.chatbot': 'एआई स्टेडियम चैटबॉट',
    'nav.planner': 'एआई मैच डे प्लानर',
    'nav.announcements': 'एआई घोषणाएं',
    'nav.notifications': 'सूचनाएं',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.settings': 'सेटिंग्स',
    'nav.logout': 'लॉगआउट',
    'dash.welcome': 'फुटबॉल विश्व कप प्रशंसक, आपका स्वागत है!',
    'dash.subtitle': 'फीफा विश्व कप 2026 के लिए तैयार हो जाइए। नीचे अपने टिकट प्रबंधित करें और स्मार्ट मार्ग की योजना बनाएं।',
    'dash.upcomingMatches': 'आगामी मैच',
    'dash.quickBooking': 'त्वरित टिकट बुकिंग',
    'dash.announcements': 'नवीनतम घोषणाएं',
    'dash.updates': 'स्टेडियम अपडेट',
    'dash.aiSuggestions': 'व्यक्तिगत एआई सुझाव',
    'book.title': 'फीफा मैच टिकट बुकिंग',
    'book.subtitle': 'विश्व कप 2026 टूर्नामेंट के प्रमुख मैचों के लिए टिकट खोजें और सुरक्षित करें।',
    'book.search': 'टीमें खोजें...',
    'book.filterStadium': 'स्टेडियम द्वारा फ़िल्टर',
    'book.filterDate': 'दिनांक द्वारा फ़िल्टर',
    'book.ticketPrice': 'मूल्य',
    'book.available': 'सीटें शेष',
    'book.button': 'टिकट बुक करें',
    'book.closed': 'बिक्री बंद',
    'seat.title': 'स्मार्ट सीट विज़ुअलाइज़र',
    'seat.subtitle': 'इंटरैक्टिव ओवरले के साथ ब्लॉक, सेक्शन और व्यक्तिगत सीटें चुनें।',
    'seat.available': 'उपलब्ध',
    'seat.reserved': 'आरक्षित',
    'seat.booked': 'बुक किया हुआ',
    'seat.vip': 'वीआईपी सीट',
    'seat.accessible': 'सुलभ सीट',
    'seat.finder': 'स्मार्ट सीट खोजक',
    'seat.aiRecommend': 'एआई सीट अनुशंसाएं',
    'seat.exitDist': 'निकास के पास',
    'seat.foodDist': 'फूड कोर्ट के पास',
    'seat.wheelchair': 'व्हीलचेयर सुलभ',
    'seat.family': 'पारिवारिक क्षेत्र',
    'seat.budget': 'किफायती सीटें',
    'seat.premium': 'प्रीमियम दृश्य',
    'seat.group': 'समूह सीटिंग',
    'seat.total': 'कुल',
    'seat.proceed': 'पुष्टि करें और बुक करें',
    'my.title': 'मेरे मैच टिकट',
    'my.active': 'सक्रिय टिकट',
    'my.past': 'पुराने टिकट',
    'my.cancelled': 'रद्द बुकिंग',
    'my.download': 'टिकट डाउनलोड करें',
    'my.cancel': 'बुकिंग रद्द करें',
    'my.refunded': 'रिफंड किया गया',
    'my.gate': 'गेट संख्या',
    'my.seat': 'सीट',
    'plan.title': 'एआई मैच डे प्लानर',
    'plan.subtitle': 'मार्ग और खाद्य समय सारिणी बनाने के लिए अपने टिकट का गेट और अनुभाग दर्ज करें।',
    'plan.create': 'स्मार्ट टाइमलाइन बनाएं',
    'plan.gate': 'टिकट गेट',
    'plan.section': 'अनुभाग',
    'plan.row': 'पंक्ति',
    'plan.seatNum': 'सीट नंबर',
    'plan.parking': 'पार्किंग क्षेत्र',
    'plan.kickoff': 'किकऑफ़ का समय',
    'plan.gatesOpen': 'गेट खुलने का समय',
    'plan.pref': 'यात्रा प्राथमिकता',
    'plan.bufferEarly': 'जल्दी आएं (भीड़ से बचें)',
    'plan.bufferStd': 'सामान्य बफ़र (1 घंटा पहले)',
    'plan.bufferTight': 'तंग बफ़र (30 मिनट पहले)',
    'plan.situation': 'स्थिति परिवर्तन या देरी?',
    'plan.adjust': 'समयरेखा बदलें',
    'chat.header': 'स्मार्टस्टेडियम एआई सहायक',
    'chat.placeholder': 'पार्किंग, गेट, हलाल भोजन के बारे में पूछें...',
    'chat.send': 'भेजें',
    'lang': 'भाषा',
  },
  pt: {
    'nav.dashboard': 'Painel',
    'nav.bookTickets': 'Reservar Bilhetes',
    'nav.myBookings': 'Minhas Reservas',
    'nav.chatbot': 'Assistente IA do Estádio',
    'nav.planner': 'Planeador de Jogos IA',
    'nav.announcements': 'Anúncios IA',
    'nav.notifications': 'Notificações',
    'nav.profile': 'Perfil',
    'nav.settings': 'Definições',
    'nav.logout': 'Sair',
    'dash.welcome': 'Bem-vindo de volta, fã do Mundial!',
    'dash.subtitle': 'Prepare-se para o Campeonato do Mundo da FIFA 2026. Gerencie bilhetes, planeie rotas e explore assentos inteligentes.',
    'dash.upcomingMatches': 'Próximos Jogos',
    'dash.quickBooking': 'Reserva Rápida',
    'dash.announcements': 'Últimos Anúncios',
    'dash.updates': 'Atualizações do Estádio',
    'dash.aiSuggestions': 'Sugestões IA Personalizadas',
    'book.title': 'Reserva de Bilhetes FIFA',
    'book.subtitle': 'Procure e garanta bilhetes para os grandes jogos da Copa 2026.',
    'book.search': 'Pesquisar seleções...',
    'book.filterStadium': 'Filtrar por Estádio',
    'book.filterDate': 'Filtrar por Data',
    'book.ticketPrice': 'Preço',
    'book.available': 'lugares restantes',
    'book.button': 'Comprar Bilhete',
    'book.closed': 'Vendas Fechadas',
    'seat.title': 'Visualizador de Lugares Inteligente',
    'seat.subtitle': 'Escolha setores e assentos individuais de forma interativa.',
    'seat.available': 'Disponível',
    'seat.reserved': 'Reservado',
    'seat.booked': 'Vendido',
    'seat.vip': 'Assento VIP',
    'seat.accessible': 'Acessível',
    'seat.finder': 'Buscador de Lugares Inteligente',
    'seat.aiRecommend': 'Recomendações de Lugares por IA',
    'seat.exitDist': 'Perto da Saída',
    'seat.foodDist': 'Perto da Restauração',
    'seat.wheelchair': 'Acessível a cadeira de rodas',
    'seat.family': 'Área Familiar',
    'seat.budget': 'Assentos Económicos',
    'seat.premium': 'Vista Premium',
    'seat.group': 'Lugares de Grupo',
    'seat.total': 'Total',
    'seat.proceed': 'Confirmar e Reservar',
    'my.title': 'Meus Bilhetes de Jogo',
    'my.active': 'Bilhetes Ativos',
    'my.past': 'Bilhetes Passados',
    'my.cancelled': 'Reservas Canceladas',
    'my.download': 'Descarregar Bilhete',
    'my.cancel': 'Cancelar Reserva',
    'my.refunded': 'Reembolsado',
    'my.gate': 'Portão',
    'my.seat': 'Lugar',
    'plan.title': 'Planeador de Jogos por IA',
    'plan.subtitle': 'Insira a porta e setor para criar o seu plano de chegada e itinerário de alimentação.',
    'plan.create': 'Gerar Cronograma Inteligente',
    'plan.gate': 'Portão de Entrada',
    'plan.section': 'Setor',
    'plan.row': 'Fila',
    'plan.seatNum': 'Número do Assento',
    'plan.parking': 'Parque de Estacionamento',
    'plan.kickoff': 'Hora do Jogo',
    'plan.gatesOpen': 'Abertura de Portões',
    'plan.pref': 'Preferência de Itinerário',
    'plan.bufferEarly': 'Chegar cedo (Evitar multidões)',
    'plan.bufferStd': 'Margem padrão (1 hora antes)',
    'plan.bufferTight': 'Margem apertada (30 min antes)',
    'plan.situation': 'Alteração de situação ou atraso?',
    'plan.adjust': 'Ajustar Cronograma',
    'chat.header': 'Assistente IA NexArena',
    'chat.placeholder': 'Pergunte-me sobre estacionamento, portões, comida halal...',
    'chat.send': 'Enviar',
    'lang': 'Idioma',
  },
  de: {
    'nav.dashboard': 'Dashboard',
    'nav.bookTickets': 'Tickets buchen',
    'nav.myBookings': 'Meine Buchungen',
    'nav.chatbot': 'KI-Stadion-Chatbot',
    'nav.planner': 'KI-Matchday-Planer',
    'nav.announcements': 'KI-Ankündigungen',
    'nav.notifications': 'Benachrichtigungen',
    'nav.profile': 'Profil',
    'nav.settings': 'Einstellungen',
    'nav.logout': 'Abmelden',
    'dash.welcome': 'Willkommen zurück, WM-Fan!',
    'dash.subtitle': 'Machen Sie sich bereit für die FIFA Fussball-Weltmeisterschaft 2026. Verwalten Sie Tickets, planen Sie Routen und nutzen Sie smarte Sitzplatz-Tools.',
    'dash.upcomingMatches': 'Anstehende Spiele',
    'dash.quickBooking': 'Schnelle Ticketbuchung',
    'dash.announcements': 'Neueste Ankündigungen',
    'dash.updates': 'Stadion-Updates',
    'dash.aiSuggestions': 'Personalisierte KI-Vorschläge',
    'book.title': 'FIFA Match Ticketbuchung',
    'book.subtitle': 'Durchsuchen und sichern Sie sich Tickets für die wichtigsten Spiele der WM 2026.',
    'book.search': 'Teams suchen...',
    'book.filterStadium': 'Nach Stadion filtern',
    'book.filterDate': 'Nach Datum filtern',
    'book.ticketPrice': 'Preis',
    'book.available': 'Plätze übrig',
    'book.button': 'Tickets buchen',
    'book.closed': 'Verkauf geschlossen',
    'seat.title': 'Smarter Sitzplatz-Visualisierer',
    'seat.subtitle': 'Wählen Sie Blöcke und Einzelsitzplätze auf der interaktiven Karte aus.',
    'seat.available': 'Verfügbar',
    'seat.reserved': 'Reserviert',
    'seat.booked': 'Gebucht',
    'seat.vip': 'VIP-Sitzplatz',
    'seat.accessible': 'Barrierefrei',
    'seat.finder': 'Smarter Sitzplatzfinder',
    'seat.aiRecommend': 'KI-Sitzplatzempfehlungen',
    'seat.exitDist': 'Nahe am Ausgang',
    'seat.foodDist': 'Nahe am Food-Court',
    'seat.wheelchair': 'Rollstuhlgerecht',
    'seat.family': 'Familienbereich',
    'seat.budget': 'Günstige Sitzplätze',
    'seat.premium': 'Premium-Aussicht',
    'seat.group': 'Gruppensitzplätze',
    'seat.total': 'Gesamt',
    'seat.proceed': 'Bestätigen und Buchen',
    'my.title': 'Meine Match-Tickets',
    'my.active': 'Aktive Tickets',
    'my.past': 'Vergangene Tickets',
    'my.cancelled': 'Stornierte Buchungen',
    'my.download': 'Ticket herunterladen',
    'my.cancel': 'Buchung stornieren',
    'my.refunded': 'Rückerstattet',
    'my.gate': 'Tor',
    'my.seat': 'Sitzplatz',
    'plan.title': 'KI-Matchday-Planer',
    'plan.subtitle': 'Geben Sie Einlasstor und Block ein, um Ihre Anfahrtsroute und Gastronomie-Pausen zu optimieren.',
    'plan.create': 'Smarte Timeline erstellen',
    'plan.gate': 'Einlasstor',
    'plan.section': 'Sektor',
    'plan.row': 'Reihe',
    'plan.seatNum': 'Sitzplatznummer',
    'plan.parking': 'Parkplatz',
    'plan.kickoff': 'Anstoßzeit',
    'plan.gatesOpen': 'Stadionöffnung',
    'plan.pref': 'Ablaufpräferenz',
    'plan.bufferEarly': 'Früh ankommen (Stau vermeiden)',
    'plan.bufferStd': 'Standard-Puffer (1 Std. vorher)',
    'plan.bufferTight': 'Knapper Puffer (30 Min. vorher)',
    'plan.situation': 'Verzögerung oder Planänderung?',
    'plan.adjust': 'Timeline anpassen',
    'chat.header': 'NexArena KI-Assistent',
    'chat.placeholder': 'Fragen Sie nach Parkplätzen, Toren, Halal-Food...',
    'chat.send': 'Senden',
    'lang': 'Sprache',
  },
  ja: {
    'nav.dashboard': 'ダッシュボード',
    'nav.bookTickets': 'チケット予約',
    'nav.myBookings': '予約履歴',
    'nav.chatbot': 'AIスタジアムチャットボット',
    'nav.planner': 'AIマッチデイプランナー',
    'nav.announcements': 'AI安全アナウンス',
    'nav.notifications': '通知センター',
    'nav.profile': 'プロフィール',
    'nav.settings': 'システム設定',
    'nav.logout': 'ログアウト',
    'dash.welcome': 'ワールドカップファンへようこそ！',
    'dash.subtitle': 'FIFAワールドカップ2026に向けて準備しましょう。チケットの管理、スタジアム経路、スマート座席機能が利用可能です。',
    'dash.upcomingMatches': '今後の注目マッチ',
    'dash.quickBooking': 'クイックチケット予約',
    'dash.announcements': '最新のお知らせ',
    'dash.updates': 'スタジアム混雑状況',
    'dash.aiSuggestions': 'AIからのあなたへのおすすめ',
    'book.title': 'FIFAワールドカップチケット予約',
    'book.subtitle': 'W杯2026トーナメントの主要試合のチケットを検索し、スマートに予約します。',
    'book.search': 'チーム名で検索...',
    'book.filterStadium': 'スタジアムで絞り込み',
    'book.filterDate': '日程で絞り込み',
    'book.ticketPrice': '価格',
    'book.available': '残席あり',
    'book.button': '座席を選択する',
    'book.closed': '販売終了',
    'seat.title': 'スマートスタジアム座席マップ',
    'seat.subtitle': 'インタラクティブな座席マップからエリアと個別席を選択できます。',
    'seat.available': '空席',
    'seat.reserved': '予約中',
    'seat.booked': '販売済',
    'seat.vip': 'VIP席',
    'seat.accessible': '車椅子・優先席',
    'seat.finder': 'スマート座席ファインダー',
    'seat.aiRecommend': 'AIおすすめ座席の比較',
    'seat.exitDist': '出口近く',
    'seat.foodDist': 'フードコート近く',
    'seat.wheelchair': '車椅子対応スペース',
    'seat.family': 'ファミリーエリア',
    'seat.budget': '格安シート',
    'seat.premium': 'プレミアムビュー',
    'seat.group': 'グループ並び席',
    'seat.total': '合計金額',
    'seat.proceed': 'この席でチケットを購入する',
    'my.title': 'マインチケット',
    'my.active': '有効なチケット',
    'my.past': '過去のイベント',
    'my.cancelled': 'キャンセル済みの予約',
    'my.download': 'eチケットダウンロード',
    'my.cancel': '予約をキャンセルする',
    'my.refunded': '返金済み',
    'my.gate': '入場口',
    'my.seat': '座席',
    'plan.title': 'AIマッチデイプランナー',
    'plan.subtitle': 'チケットのゲートや座席座標を入力するだけで、パーソナライズされた入場ルートや食事のタイムラインを作成します。',
    'plan.create': 'スマートタイムラインを生成',
    'plan.gate': 'チケットゲート',
    'plan.section': 'セクション',
    'plan.row': '列',
    'plan.seatNum': '座席番号',
    'plan.parking': '駐車場',
    'plan.kickoff': 'キックオフ時間',
    'plan.gatesOpen': '開門時間',
    'plan.pref': 'タイムライン優先設定',
    'plan.bufferEarly': '早めの到着（混雑回避）',
    'plan.bufferStd': '標準到着（1時間前目安）',
    'plan.bufferTight': 'ギリギリ到着（30分前目安）',
    'plan.situation': '交通渋滞や到着遅れ等の状況変化？',
    'plan.adjust': 'スケジュールを再調整',
    'chat.header': 'スタジアムAIアシスタント',
    'chat.placeholder': '駐車場、ゲート、ハラルフードについて質問する...',
    'chat.send': '送信',
    'lang': '言語',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const cached = localStorage.getItem('ss_lang') as Language;
    return cached && TRANSLATIONS[cached] ? cached : 'en';
  });

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('ss_lang', lang);
  };

  const translate = (key: string): string => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.en;
    return dict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t: translate }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
export const LANGUAGES_LIST = [
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español' },
  { code: 'fr', label: 'Français' },
  { code: 'ar', label: 'العربية' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'pt', label: 'Português' },
  { code: 'de', label: 'Deutsch' },
  { code: 'ja', label: '日本語' }
] as const;
